# Generated by Django 5.0.6 on 2024-05-14 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentification', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('CREATOR', 'Createur'), ('SUBSCRIBER', 'Abonne')], max_length=30),
        ),
    ]
