# Generated by Django 5.0.6 on 2024-05-10 13:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Announce',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Band',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('danger_level', models.CharField(choices=[('UWN', 'Non Specified'), ('SFE', 'Safe'), ('LOW', 'Low'), ('MED', 'Med'), ('S', 'High'), ('SS', 'S High'), ('SSS', 'Extreme')], default='UWN', max_length=3)),
                ('year_formed', models.IntegerField(default=2000, validators=[django.core.validators.MinValueValidator(1800), django.core.validators.MaxValueValidator(2024)])),
                ('active', models.BooleanField(default=True)),
                ('biography', models.CharField(default='', max_length=1000)),
                ('official_homepage', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
